django-bar/malybar/malybar/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^', include('pizza.urls', namespace='pizza')),
    url(r'^pizza/', include('pizza.urls', namespace='pizza')),
    url(r'^konta/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
]

django-bar/malybar/pizza/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views  # import widoków aplikacji
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from .models import Pizza
from .models import Skladnik

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^kontakt$',views.kontakt, name='kontakt'),
    url(r'^lista/', login_required(ListView.as_view(model=Pizza)),
        name='lista'),
    url(r'^listas/', login_required(ListView.as_view(model=Skladnik)),
        name='listas'),
    url(r'^dodaj/$', views.PizzaCreate.as_view(), name='dodaj'),
]

django-bar/malybar/pizza/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Pizza(models.Model):
    LARGE = 'L'
    MEDIUM = 'M'
    SMALL = 'S'
    ROZMIARY = (
        (LARGE, 'duża'),
        (MEDIUM, 'średnia'),
        (SMALL, 'mała'),
    )
    nazwa = models.CharField(verbose_name='Pizza', max_length=30)
    opis = models.TextField(blank=True, help_text='Opis Pizzy')
    rozmiar = models.CharField(max_length=1, choices=ROZMIARY, default=LARGE)
    cena = models.DecimalField(max_digits=5, decimal_places=2)
    data = models.DateField('dodano', auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)

    def __unicode__(self):
        return u'%s' % (self.nazwa)

    class Meta:
        verbose_name_plural = 'pizze'


class Skladnik(models.Model):
    pizza = models.ForeignKey(Pizza, related_name='skladniki')
    nazwa = models.CharField(verbose_name=u"składnik", max_length=30)
    jarski = models.BooleanField(
        default=False,
        verbose_name=u"jarski?",
        help_text=u"Zaznacz, jeżeli składnik jest odpowiedni dla"
        u" wegetarian")

    def __unicode__(self):
        return u'%s' % (self.nazwa)

    class Meta:
        verbose_name_plural = u'składniki'

django-bar/malybar/pizza/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm, Textarea
from . import models
from django.forms.models import inlineformset_factory


class PizzaForm(ModelForm):

    class Meta:
        model = models.Pizza
        exclude = ('data', 'autor')
        widgets = {'opis': Textarea(attrs={'rows': 2, 'cols': 80})}


SkladnikiFormSet = inlineformset_factory(
    parent_model=models.Pizza,
    model=models.Skladnik,
    max_num=6,
    min_num=1,
    validate_max=True,
    validate_min=True,
    extra=2,
    fields=('nazwa', 'jarski')
)

django-bar/malybar/pizza/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from . import models
from . import forms
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect


def index(request):
    """Strona główna"""
    kontekst = {'komunikat': 'Witaj w aplikacji Pizza!'}
    return render(request, 'pizza/index.html', kontekst)

def kontakt(request):
    """Strona główna"""
    kontekst = {'kontakt': 'To jest kontakt!'}
    return render(request, 'pizza/kontakt.html', kontekst)

@method_decorator(login_required, 'dispatch')
class PizzaCreate(CreateView):
    """Widok dodawania pizzy i skladników."""

    model = models.Pizza
    form_class = forms.PizzaForm
    success_url = reverse_lazy('pizza:lista')  # '/pizza/lista'

    def get_context_data(self, **kwargs):
        context = super(PizzaCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['skladniki'] = forms.SkladnikiFormSet(self.request.POST)
        else:
            context['skladniki'] = forms.SkladnikiFormSet()
            context['imie']='Kasia'
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        skladniki = forms.SkladnikiFormSet(self.request.POST)
        if form.is_valid() and skladniki.is_valid():
            return self.form_valid(form, skladniki)
        else:
            return self.form_invalid(form, skladniki)

    def form_valid(self, form, skladniki):
        form.instance.autor = self.request.user
        self.object = form.save()
        skladniki.instance = self.object
        skladniki.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, skladniki):
        return self.render_to_response(
            self.get_context_data(form=form, skladniki=skladniki)
        )

django-bar/malybar/pizza/templates/pizza/index.html
<h1>Mały Bar</h1>
<p>{{ komunikat }}</p>
<ul>
  {% if not user.is_authenticated %}
    <li><a href="{% url 'auth_login' %}">Zaloguj się</a></li>
    <li><a href="{% url 'registration_register' %}">Utwórz konto</a></li>
  {% else %}
    <li><a href="{% url 'auth_logout' %}">Wyloguj się</a></li>
  {% endif %}
</ul>

<p><a href="{% url 'pizza:lista' %}">Lista pizz</a></p>
<p><a href="{% url 'pizza:listas' %}">Lista składników</a></p>

django-bar/malybar/pizza/templates/pizza/kontakt.html
<h1>Mały Bar</h1>
<p>{{ kontakt }}</p>
<p>Na sztywno umieszczona treść, ona nie jest dynamiczna.</p>

django-bar/malybar/pizza/templates/pizza/pizza_form.html
<h1>Dodaj pizzę</h1>

<form action="." method="post" id="pform">
    {% csrf_token %}
    {{ form.as_p }}

    <h3>Składniki:</h3>
    {{ skladniki.management_form }}
    {{ skladniki.non_form_errors }}
    {% for skl in skladniki %}
    {{ skl.id }}
        <div class="{{ skladniki.prefix }}">
            <span>{{ forloop.counter }})&nbsp;</span>       {{ skl.nazwa.errors }}
            {{ skl.jarski.errors }}
            {{ skl.nazwa.label_tag }} {{ skl.nazwa }}
            {{ skl.jarski.label_tag }} {{ skl.jarski }}
        </div>
    {% endfor %}
    <br /><input type="submit" value="Zapisz">
</form>
<h1>{{imie}}</h1>

django-bar/malybar/pizza/templates/pizza/pizza_list.html
<h1>Lista pizz</h1>

<table class="table">
<tr><th>Lp.</th><th>Nazwa</th><th>Info</th><th>Operacje</th></tr>
{% for p in object_list %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ p.nazwa }}</td>
    <td>{{ p.autor.username }} ({{ p.data }})</td>
    <td>
        {% if p.autor.username == user.username %}
            <a href="#">Edytuj</a> &bull;
            <a href="#">Usuń</a>
        {% endif %}
    </td>
</tr>
{% endfor %}
</table>

django-bar/malybar/pizza/templates/pizza/skladnik_list.html
<h1>Lista składników</h1>

<table class="table">
<tr><th>Lp.</th><th>Nazwa</th><th>Pizza</th><th>Jarski</th></tr>
{% for p in object_list %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ p.nazwa }}</td>
    <td>{{ p.pizza.nazwa}}</td>
    <td>{{ p.jarski}}</td>
    <td>{% if p.autor.username == user.username %}
            <a href="#">Edytuj</a> &bull;
            <a href="#">Usuń</a>
        {% endif %}
    </td>
</tr>
{% endfor %}
</table>